title: Lineup
hero_image: images/banner.png
description: Create a game to find a character amongst a sea of other characters
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-05
steps: 
- title: Introduction
- title: Import your costumes
- title: Making a grid
- title: Testing the script
- title: Stamping a row
- title: Changing the costumes
- title: Adding rows
- title: Placing your sprite
- title: Finishing the game
- title: "Challenge: taking it further"
  challenge: true
- title: "What next?"