---
title: Line up
hero_image: images/banner.png
description: Create a game where you look for a character hidden in a crowd of other characters
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-05-01
steps:
  - 
    title: Introducción
  - 
    title: Add costumes
  - 
    title: Create a grid
  - 
    title: Test the script
  - 
    title: Stamp a row
  - 
    title: Change the costumes
  - 
    title: Add rows
  - 
    title: Hide your sprite
  - 
    title: Finish the game
  - 
    title: "Desafío: mejora tu juego"
    challenge: true
  - 
    title: "Desafío: Pantalla de instrucciones"
