---
title: Todos en fila
hero_image: images/banner.png
description: Crea un juego en el que busques un personaje oculto en una multitud de otros personajes
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-05
steps:
  - 
    title: Introducción
  - 
    title: Añade disfraces
  - 
    title: Crea una cuadrícula
  - 
    title: Prueba el script
  - 
    title: Sella una fila
  - 
    title: Cambia los disfraces
  - 
    title: Añade filas
  - 
    title: Oculta tu objeto
  - 
    title: Termina el juego
  - 
    title: "Desafío: mejora tu juego"
    challenge: true
  - 
    title: "¿Qué sigue?"
