---
title: Line up
hero_image: images / banner.png
description: Create a game where you look for a character hidden in a crowd of other characters
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-05
steps:
  - 
    title: Wprowadzenie
  - 
    title: Add costumes
  - 
    title: Create a grid
  - 
    title: Test the script
  - 
    title: Stamp a row
  - 
    title: Change the costumes
  - 
    title: Add rows
  - 
    title: Hide your sprite
  - 
    title: Finish the game
  - 
    title: "Wyzwanie: udoskonal swoją grę"
    challenge: true
  - 
    title: "Co następne?"
