---
title: Στοιχηθείτε!
hero_image: images/banner.png
description: Δημιούργησε ένα παιχνίδι όπου αναζητάς ένα χαρακτήρα κρυμμένο ανάμεσα σε πολλούς άλλους χαρακτήρες
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-05
steps:
  - title: Εισαγωγή
  - title: Προσθήκη ενδυμασιών
  - title: Δημιούργησε μια κάναβο
  - title: Δοκίμασε το πρόγραμμα
  - title: Σφραγίστε μια σειρά
  - title: Άλλαξε τις ενδυμασίες
  - title: Προσθέστε σειρές
  - title: Κρύψε το αντικείμενό σου
  - title: Τελείωσε το παιχνίδι
  - title: "Πρόκληση: βελτίωσε το παιχνίδι σου"
    challenge: true
  - title: "Και τώρα;"
