---
title: Line up
hero_image: images/banner.png
description: Create a game where you look for a character hidden in a crowd of other characters
listed: true
copyedit: true
version: 4
last_tested: 05.11.2018
steps:
  - 
    title: Introduction
  - 
    title: Add costumes
  - 
    title: Create a grid
  - 
    title: Test the script
  - 
    title: Stamp a row
  - 
    title: Change the costumes
  - 
    title: Add rows
  - 
    title: Hide your sprite
  - 
    title: Finish the game
  - 
    title: "Défi : Améliorez votre jeu"
    challenge: true
  - 
    title: "Défi: Écran d'instruction"
